### ISSUE TITLE
Search for members by email address

### ISSUE THREAD

**Issue by Kpapadak1** [kwartzlab/kos-base#55]
We are unable to search for members by their email address. It would help the board in finding people that email in but do not specify a name.

**Comment by azend** [comment]
Looking at the code, the library used to search and filter the table currently searches the entire contents of the table on the client side. However, the server side view does not extract or present email addresses to the client side inside the table.

Is there concern around member email addresses being visible to other members? Given all filtering currently is done client side, we may be able to hide the data from visibility. But someone clever will still be able to extract the data from the raw markup if they were so motivated.

**Comment by azend** [comment]
As per discussion on Slack, it looks like there's no issue. https://kwartzlab.slack.com/archives/CE19BV0F6/p1726528716553699
