### ISSUE TITLE
Update config/kwartzlabos.php membership_coordinator

### ISSUE THREAD

**Issue by sarahjonesmilligan** [kwartzlab/kos-base#56]
Please update the config for membership coordinator name to Laura Schuhbauer.

**Comment by Schuhbauer12** [comment]
Can we actually just make it neutral? It doesn't need to have a specific name, just leave it with the job title (aka Membership Coordinator) so we don't have do this every year.

**Comment by Schuhbauer12** [comment]
Also, the slack link is expired? So when I set a member to active, it's sending them an expired slack link. I can create a new one if others cannot.
