### ISSUE TITLE
Revoke all access to a tool

### ISSUE THREAD

**Issue by sarahjonesmilligan** [kwartzlab/kos-base#88]
It doesn't happen often, but sometimes we want to revoke all users of a tool to force them to be retrained. Having to revoke and confirm each user one at a time is time consuming. Having a means to revoke all authorizations would be useful. 

(e.g. https://kos.kwartzlab.ca/gatekeepers/14/dashboard for new table saw we're forcing retraining for everyone with a new table saw)

**Comment by everett-ripley** [comment]
I have a working system to revoke all access to a tool. The issue now is formatting and authorization. Currently the revoke all access feature requires the same authorization as anything else in a gatekeeper's dashboard, but I'm wondering if it should be changed to just BoD members.
I've also included an image to where I think the button should go, it's fairly out of the way to prevent accidental clicks, but I don't want to make any lasting design decisions without feedback.

![image](https://github.com/user-attachments/assets/5635fa8c-6767-42d6-b00e-4e0bd4d75454)

**Comment by sarahjonesmilligan** [comment]
If someone accidentally clicked it, is there any past history stored (even if not easily accessible)?

We might want to restrict it more if there's no hope of recovery

**Comment by sarahjonesmilligan** [comment]
Ugh

**Comment by azend** [comment]
@everett-ripley didn't mention it but the button he's built a feature for requires clicking through a confirmation dialogue for the function to take action. It's still possible to make a mistake but not quite as easy.
